volumes:
  sql-volume:

services:
  sqlserver:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1443:1443
    volumes: 
      - sql-volume:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: woRrrrrrD1209!!
      MSSQL_PID: Express
      MSSQL_TCP_PORT: 1443
      
  web-api-learning:
    container_name: service-api
    image: web-api-learning
    build: ./web-api-learning
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - sqlserver
    restart: on-failure