services:
  sql-server-db:
    container_name: sql-server
    user: root
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1443:1443
    volumes: 
      - sql-volume:/var/opt/mssql/data    
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - MSSQL_TCP_PORT=${MSSQL_TCP_PORT}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      
  web-api-learning:
    container_name: service-api
    image: web-api-learning
    build: ./web-api-learning
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - sql-server-db
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}

volumes:
  sql-volume: