volumes:
  pgdata:
  sql-volume:

networks:
  traefik:
    external: true
    driver: overlay
  solution-net:

services:
  sql-server-db:
    user: root
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1443:1443
    volumes:
      - sql-volume:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - MSSQL_TCP_PORT=${MSSQL_TCP_PORT}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    networks:
      - solution-net
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        delay: 10s
      restart_policy:
        condition: on-failure

  service-api:
    image: test:latest # using the latest tag is highly discouraged
    networks:
      - traefik
      - solution-net
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.api.rule=Host(api.my-net.here)
        - traefik.http.services.api.loadbalancer.server.port=9090
